### PR TITLE
Test PR for my refreshed fork.

### PR DESCRIPTION
**Pull request by ACIIL**
For the purpose of improving commit history and not rebasing old forgotten merges again i have restarted my fork (from the master) and pasted my backup code over it. This code does have sync pulls from the master's updates.

Code additions should be exactly like my last pull request attempt and its comments #149.

I have made no attempt to sync with the master's updates. This pull is from work done months ago and became stale.  Combining my improvement into the master will likely not be my battle at this point.

### CODE REVIEW

**Comment by ACIIL** [comment]
Reminder that the chromosome layout has changed. You can use my example chromosome and run `Simulator.prototype.evalMutations("mass");` to see performance.

**Comment by reconman** [comment]
You've reverted some of my commits so I'll look through the changes line by line and then commit your changes only.

**Comment by ACIIL** [comment]
Except for merge critical code, please make your preferable changes after this pull acceptance, so that i can track it in github.  I noticed you make non-functional changes during the pull requests and not after as a separate individual pull request.  I know this is a off-shoot branch, so every pull request i make is superficial until i have acceptance to pull my work in the real official branch, and then work from there.

I have no idea what commit differences there are or that there would be. This backup is be the same from when i attempted the first pull request and from what state my fork was.  It was already stale without updates and for weeks + delay.   

If there is some kind of "staging branch" where this pull request sits and i can watch what you are doing, i want to see it on github (just noticed the invisible "files changes" tab above). I make assumption a pull request on github can only be what this page gives me to work with.

Edit: **Also. I have no idea what i am doing anymore.**

**Comment by calexil** [comment]
@ACIIL  we've all been there

**Comment by reconman** [comment]
You've created the pull request in your fork instead of in the base repository. I've created a pull request for you and merged it.

I have reviewed all changes and corrected the parts you have reverted to previous versions. I've also replaced all your indentations with spaces to tabs.

Now I only need to know a bit about your changes of strategy.js. You have introduced lots of new logic with tons of variables and I don't understand most of it.

Could you please merge my commit https://github.com/synkarius/saltbot/commit/e947faece64c5129fcc440b85b5b59ab5605f7cf and add comments in the new or revised parts of strategy.js?

**Comment by ACIIL** [comment]
> You've created the pull request in your fork instead of in the base repository. I've created a pull request for you and merged it.

Wait, what. Did i just pull request myself?   I think i did. I am a idiot in my frustration.  Glad you guys even noticed this but damn. Good thing i made this as a test.

**Comment by ACIIL** [comment]
I will get on your merge and study what comments to improve. Removing my fork actually removed usefull wiki documents that explained the changes and internal variable which otherwise need a flashlight to show how they change the behavior of betting prediction and evolution simulation.

**Comment by ACIIL** [comment]
_Think i need a better place to document the changes._ Perhaps a wiki page in the synkarius page, or write a document somewhere?  Some note will be more detailed then what code comments will allow and i do not want to flood the code with lines of meaning behind each variable.  I do not find this comment area appropriate ether....
.
.
.
.
.
I am going to take a guess here what you might be missing at this time, **this stuff would be saved elsewhere again when i know where to:**
.
.
-You **Must start with a new pool, a chromosome was provided to start immediately**. Test performance with Simulator.prototype.evalMutations("mass"); as you know how to use this,  i made it more detailed and look for certain behavior for good selection here.  _You do not want only a high accuracy % now, but high gain %_ (+8% with the huge match data records).  You also _want it to have lower (NEW) "missed gains" than losses saved (forgot wording), and losses saved high (testing had it around +25%)._ Know these two scores also count moments where match prediction had a penalty, so when the sim is testing everything every single low data match counted for how right the chromosome was (and affecting the inverted confidence value it reports).
.
.

-If your confusion is inside `ConfidenceScore.prototype.execute = function (info) {`  I would need to get very detailed, as there was a problem _where i realized i needed to move code_ into the` var CSStats = function (cObj, chromosome) {`  in _part of changing how low sample characters are not biased with better/worse averages but instead go towards a mean if samples are lower than max character records stored internally_, most lines scoring character stats were staged to be simplified before i stopped updating months ago.  The code has useless lines marked with variable name schemes like `----RatioTemper` that i think are confusing you. Again this area needed work but i left it as is in my pause, i would need to refactor and track character stats sample sizes in the  `CSStats`  class before i can continue here. 
.
.
-The Critical The point  of the ` ConfidenceScore.prototype.execute` _changes is to make the character 1 & 2 score not be a tallying "+score"_ if they have the favorable stats, _but make score scaled by how well the characters stats compare_, and making the prediction measuring more continuous in math (commit history mentioned). This changed the chromosome selection is a dramatic way. 
.
.
-Another edit in prediction is _i reversed scoring for the character whom has a highest average odds,_ it will now give scaled points to the low odds character, _this made the prediction for upsets surprising high when trained for_ (and keeping it conservative when betting wrong.....  But i digress, i want to write this somewhere else better. 
.
.
-Code change to how _scientist tournament prediction is scaled with a range transform_. I had a past issue that touched on meaning.
.
.
-_more i forgot_ and would need to write proper documents, or just talk to you directly as you review.
.
.
.
.
.
-The **ABSOLUTE** most important var that needs user access (and you should study outwards from here) is `var weightAccToMoney = ` starting at its default `0.75 ` inside popup.js, _it controls how chromosomes are selected and is prime to affecting every changed i made._ It can make the machine train to bet from upsets with out heavy losses or to mostly betting right conservatively. It works well because of all subtle changes to chromosome evolution was made to be more delicate and precise, and changing the match prediction behavior to be more precise guessing skill between opponents.  I had a past issue for adding user config vars for this value and i failed to do so.
.
.
.
.
.
Not sure how you would study the code, but from outside my diffs:
From and and inside `Simulator.prototype.evalMutations = function (mode) {`  - below line ` var characterRecords = [];` see and how stats printouts changed, how the pool is scored, sorted by best, and next gen pool generation. The next pool generation code  has many vars that i have commented.  I think you will look at this for a while.

From in `ConfidenceScore.prototype.execute = function (info) {` , i said a few changes above, the overhaul form more precise character stats scoring & improve prediction, etc...

**Comment by calexil** [comment]
@ACIIL You can use the subreddit wiki!!

https://www.reddit.com/r/saltbot/

message me on reddit so I can add you as a moderator

then you can edit the wiki directly

**Comment by ACIIL** [comment]
Should of said this again. I will never use reddit. I hate reddit.

**Comment by reconman** [comment]
There's also https://github.com/synkarius/saltbot/wiki

**Comment by ACIIL** [comment]
Likely a good time to start a wiki page for the bot too. I looked at before and found the  honor for first page was not mine. I can explain the bot behavior like the back of my hand now. lol

 I will dump and improve this info into a temperately page to review....Later when energetic.

**Comment by ACIIL** [comment]
https://github.com/synkarius/saltbot/wiki/New-mutation-branch-development-Notes-(temperately)

**Pull request closed without merging**
